### ISSUE TITLE
Organising ports into registers

### ISSUE THREAD

**Issue by lmondada** [CQCL/portgraph#8]
I want to discuss a point that I have mentioned before. I do not claim that my proposal is the right one -- I just want this to be discussed explicitly and gather everyone's opinion. All I can say is that from my pattern matching perspective, this design change would make the code logic cleaner and simpler.

## The problem with input-output ports
Right now, the design of the library splits ports into two categories: input ports and output ports. This is natural for directed graphs (which is what we care about 95% of the time), but is strictly speaking redundant: each port has a unique ID anyways. It also doubles the API interface (every function must have a in-port and out-port version) and makes code that does not care about directedness (or cares about more than just directedness) a bit awkward to write. 

Adding a direction-agnostic API works, but now the number of function has tripled.

It also makes it impossible to express undirected graphs, such as any ZX-inspired representation.

## Proposal: port registers
As an alternative, I'd suggest grouping ports into registers. Directed port graphs could then have `in` and `out` registers, with the additional constraint that edges must have one endport in each register. Gates such as `CnX` could have `ctrl_in/out` and `target_in/out` registers, and classically-controlled operations could separate classical control from qubits into registers. This would make distinguishing control bits from qubits much more elegant than relying on the "classical comes first" convention.

In the graph trie datastructure (a meta-graph used for graph pattern matching) that I am building, out-edges are indexed by `(a, b)` tuples, so having `a` registers would allow me to find the edge `(a, b)` in constant time.

Overall the API would be simpler and more general and would come at zero cost, I think: it would be straight forward to implement a thin wrapper on top of an undirected portgraph that exposes exactly the same directed API that exists today, with the exact same underlying representation.

## Implementation
I propose replacing the `incoming` and `outgoing` fields in `NodeMeta` by a list of offsets. I would be in favour of pretty stringent limits on the size and number of such registers, so that the entire list can be stored in a fixed-size field (eg max 16 ports per register, max 8 registers = 32 bits). If instead of register length we want register offset for constant `PortIndex` access we might need 64 bits.

To address port registers by name, we would need either to fix the register names for the entire graph at construction time (e.g. directed graphs), or they could be dependent on node weights (e.g. quantum gates with different registers). Or just define enums with explicit conversions to integers!

## Disadvantages
The main drawbacks I see is more stringent limits on port register sizes (if we want to keep the node representation concise) as well as slightly more indirection in the code for directed graphs -- but all of that abstraction could be optimised away at compile time, I'm pretty sure.

**Comment by aborgna-q** [comment]
Currently we have a binary `Direction::{Incoming, Outgoing}` tag for the ports, and all the linking logic makes sure to keep the invariant that edges go from one to the other.

Adding arbitrary port registers would require replacing that binary tag for a string or some dynamic equivalent. The direction tag is also embedded in the `PortMeta` so that we can check it without asking for the node metadata (this is used when checking the link invariants, and in `port_direction`). Using a bigger encoding would prevent us from using the short-circuit.

I have two main issues with this:

- Adding validity checks when having arbitrary port registers would increase the code complexity everywhere. It's not clear if we would be able to express the "outputs connect to inputs" invariant on the directed case, and we'd lose the efficient checks anyway.

- On the API side, having to explicitly put the port register name everywhere may get a bit annoying for the user. Yes, it reduces the number of methods in the API, but at the cost of extra noise on the call sites.

Since the main use of this crate is for directed crates it may be better to consider an "undirected" wrapper on top of the current thing, using doubled edges or perhaps something better.

In the meantime I would propose adding a `Direction::Any` variant to make the existing methods (`ports`, `num_ports`, `links`, ...) a bit more flexible. Or we could add a `Directions` set, to avoid sending invalid values to things like `port_index`.

**Comment by aborgna-q** [comment]
Closing this as not planned for the moment.
